a=int(input("Enter a:"))
b=int(input("Enter b:"))
print("Sum=",a+b,"\nProduct=",a*b,"\nDivision=",(a/b),"\nDifference=",a-b,"\nNew sum=",a++b,"\nNew Product=",a**b)
print("Remainder=",a%b)
print("Power=",b^a)
