a=input("Enter a string:")
print("Min=",min(a))
print("Max=",max(a))
print("Cap=",a.capitalize())
print("Center=",a.center(40))
print("Find=",a.find("a"))
print("Uppercase=",a.upper())
print("Lower case=",a.lower())
print("Swap=",a.swapcase())
print("Check Upper=",a.isupper())
print("Check Lower=",a.islower())
print("Length=",len(a))
print("Count of a=",a.count("a"))
e=(input("Enter the value of e:"))
print("Count of ",e + " is",a.count(e))